Add Various bug fixes and finish style fixes

diff --git a/bin/insta485run b/bin/insta485run
--- a/bin/insta485run
+++ b/bin/insta485run
@@ -1,5 +1,12 @@
 #!/bin/bash
-#
+# insta485run
 
-# Start a dev server and browse to http://localhost:8000.
-flask --app insta485 --debug run --host 0.0.0.0 --port 8000
+set -Eeuo pipefail
+
+if [ ! -f var/insta485.sqlite3 ]; then
+  echo "Error: can't find database var/insta485.sqlite3"
+  echo "Try: ./bin/insta485db create"
+  exit 1
+fi
+
+flask --app insta485 run --host 0.0.0.0 --port 8000
